server.port=9090

spark.master=local[2]
spark.application-name=Machine Learning with Apache Spark
spark.distributed-libraries=file:///X:/spark-distributed-library/build/libs/spark-distributed-library-1.0-SNAPSHOT-all.jar
spark.driver.memory=2g
spark.cores.max=4
spark.executor.memory=4g
spark.default.parallelism=4
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.kryo.registrationRequired=false
spark.kryoserializer.buffer.max=128m
spark.sql.shuffle.partitions=5

dou.training.set.csv.file.path=file:///X:/training-set/dou/2016_may_mini.csv
dou.regression.model.directory.path=file:///X:/training-set/dou/regression-model
dou.clustering.model.directory.path=file:///X:/training-set/dou/clustering-model

product.training.set.csv.file.path=file:///X:/training-set/dou/2016_may_mini.csv
product.test.set.csv.file.path=file:///X:/training-set/dou/2016_may_mini.csv

lyrics.pipeline=LogisticRegressionPipeline
lyrics.training.set.directory.path=file:///X:/training-set/lyrics
lyrics.model.directory.path=file:///X:/training-set/lyrics/model

mnist.training.set.image.file.path=file:///X:/training-set/mnist/train-images-idx3-ubyte
mnist.training.set.label.file.path=file:///X:/training-set/mnist/train-labels-idx1-ubyte
mnist.test.set.image.file.path=file:///X:/training-set/mnist/t10k-images-idx3-ubyte
mnist.test.set.label.file.path=file:///X:/training-set/mnist/t10k-labels-idx1-ubyte
mnist.training.set.parquet.file.path=file:///X:/training-set/mnist/training-set.parquet
mnist.test.set.parquet.file.path=file:///X:/training-set/mnist/test-set.parquet
mnist.model.directory.path=file:///X:/training-set/mnist/model
mnist.validation.set.directory.path=file:///X:/training-set/mnist/validation-set
